### ISSUE TITLE
Initialization script errors with first run of docker image

### ISSUE THREAD

**Issue by RikEnde** [clairempr/letterpress#2]
Steps to reproduce: 

1 ) If present, remove docker image for letterpress
2) Start with a fresh clone of the letterpress repository
3) docker-compose up

result: 
```
web_1            | settings_secret module not found, creating a dummy letterpress/settings_secret.py. You will want to edit this.
web_1            | Traceback (most recent call last):
web_1            |   File "/code/letterpress/firstrun.py", line 2, in <module>
web_1            |     import letterpress.settings_secret as settings_secret
web_1            | ImportError: No module named 'letterpress.settings_secret'
web_1            | 
web_1            | During handling of the above exception, another exception occurred:
web_1            | 
web_1            | Traceback (most recent call last):
(...)
web_1            |   File "/code/letterpress/settings.py", line 8, in <module>
web_1            |     from letterpress.firstrun import settings_secret
web_1            |   File "/code/letterpress/firstrun.py", line 17, in <module>
web_1            |     settings_secret = importlib.import_module('letterpress.settings_secret')
web_1            |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1            |     return _bootstrap._gcd_import(name[level:], package, level)
web_1            | ImportError: No module named 'letterpress.settings_secret'
```

Application continues to start normally, but errors occur, because the database is empty: 

```
Request Method: | GET -- | --
https://localhost:8000/random_letter/
1.11.1
OperationalError
no such table: letters_letter
/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
/usr/local/bin/python
3.5.5
['/code',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/site-packages']
Mon, 19 Feb 2018 11:28:58 +0000
```

After the container is stopped, `db.sqlite3` and `settings_secret.py` are written as they are supposed to. Starting the container again, the applicaton runs as it is supposed to.

**Comment by clairempr** [comment]
Fixed elsewhere
